apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: greeter-source-package
  namespace: dev2
  labels:
    app.kubernetes.io/part-of: greeter-source-package
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/workload-type: server
spec:
  source:
    git:
      url: ssh://git@github.com/Mpluya/greeter-source-package.git
      ref:
        branch: main
